apiVersion: v1
kind: Service
metadata:
  name: oracledb-svc
  namespace: mooc-uat
spec:
  selector:
    app: oracledb
  externalName: host.docker.internal
  ports:
    - port: 1521
  type: ExternalName
  